#!/usr/bin/env python3
"""Emit cpp/src/glossary_data.cpp from modelfit/glossary.py.

The GUI reuses the Python-curated glossary so we only maintain one copy.
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

from modelfit.glossary import GLOSSARY, all_categories  # noqa: E402


def cstr(s: str) -> str:
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif ord(ch) < 32:
            out.append(f'\\x{ord(ch):02x}')
        else:
            out.append(ch)
    return ''.join(out)


def main() -> int:
    print('// Auto-generated by cpp/scripts/gen_glossary.py — DO NOT EDIT.')
    print('// Regenerate with: python3 cpp/scripts/gen_glossary.py > cpp/src/glossary_data.cpp')
    print('#include "modelfit/glossary.h"')
    print('namespace modelfit {')
    print('namespace gloss {')
    print()
    print(f'const std::array<GlossaryEntry, {len(GLOSSARY)}> ENTRIES = {{{{')
    for e in sorted(GLOSSARY.values(), key=lambda e: e.term.lower()):
        see = ", ".join(f'"{cstr(s)}"' for s in e.see_also) if e.see_also else ""
        print(f'    GlossaryEntry{{'
              f'"{cstr(e.term)}", '
              f'"{cstr(e.summary)}", '
              f'"{cstr(e.body)}", '
              f'"{cstr(e.analogy)}", '
              f'{{{see}}} '
              f'}},')
    print('}};')
    print()
    print(f'constexpr std::size_t ENTRY_COUNT = {len(GLOSSARY)};')
    print()
    cats = all_categories()
    print(f'const std::array<Category, {len(cats)}> CATEGORIES = {{{{')
    for cat, entries in cats.items():
        terms = ", ".join(f'"{cstr(e.term)}"' for e in entries)
        print(f'    Category{{"{cstr(cat)}", {{{terms}}}}},')
    print('}};')
    print()
    print('} // namespace gloss')
    print('} // namespace modelfit')
    return 0


if __name__ == "__main__":
    sys.exit(main())
