#!/usr/bin/env python3
"""Emit a C++ header containing the curated 206-model catalog.

Importing the Python package is the *only* way these two sides stay in
sync — any new model added to modelfit/models.py is picked up on the next
codegen run. Output is a single header that defines a `constexpr` array.

Usage:
    python3 cpp/scripts/gen_catalog.py > cpp/include/modelfit/catalog_data.h
"""
from __future__ import annotations

import os
import sys
import textwrap

# Allow running from anywhere by inserting the project root on sys.path.
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, ROOT)

from modelfit.models import get_catalog  # noqa: E402


def cstr(s: str) -> str:
    """C-escape a string."""
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ch == '\n':
            out.append('\\n')
        elif ord(ch) < 32:
            out.append(f'\\x{ord(ch):02x}')
        else:
            out.append(ch)
    return ''.join(out)


def main() -> int:
    cat = get_catalog(include_external=False)
    print('// Auto-generated by cpp/scripts/gen_catalog.py — DO NOT EDIT.')
    print('// Regenerate with:  python3 cpp/scripts/gen_catalog.py > cpp/include/modelfit/catalog_data.h')
    print('#pragma once')
    print('#include "modelfit/types.h"')
    print('#include <array>')
    print()
    print('namespace modelfit {')
    print()
    print(f'inline constexpr std::size_t CATALOG_SIZE = {len(cat)};')
    print()
    print('inline const ModelSpec CATALOG[CATALOG_SIZE] = {')
    for m in cat:
        tags = '", "'.join(m.tags)
        tags = f'"{tags}"' if m.tags else ''
        line = (
            f'    ModelSpec{{'
            f'"{cstr(m.id)}", '
            f'"{cstr(m.name)}", '
            f'"{cstr(m.family)}", '
            f'{m.params_b:.3f}, '
            f'{m.active_params_b:.3f}, '
            f'{m.context_max}, '
            f'"{m.type}", '
            f'{m.quality:.2f}, '
            f'{m.kv_bytes_per_token}, '
            f'{{{tags}}}'
            f'}},'
        )
        print(line)
    print('};')
    print()
    print('} // namespace modelfit')
    return 0


if __name__ == "__main__":
    sys.exit(main())
